project:
  type: website

website:
  title: "biostat777-intro-GuanGui.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example Analysis
      - href: part1.qmd
        text: Part 1
      - href: part3.qmd
        text: Part 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
