project:
  type: website

website:
  title: "biostat777-intro-GuanGui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example Analysis
      - href: part1.qmd
        text: Part 1
      - href: part3.qmd
        text: Part 3

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual
