---
title: "Part 1: Defining My Scientific Brand"
format: html
---

# Defining My Scientific Brand

## Who am I? What makes me special?

I am Guan Gui, a first-class honors graduate in Data Science from the University of Sydney, currently pursuing my ScM in Biostatistics at Johns Hopkins University. I have a keen sensitivity to data and extensive experience in data analysis, with a strong passion for biomedical data, especially in the field of spatial genomics.

## What do I stand for?

I am dedicated to uncovering new insights from biomedical data, particularly in cancer and neurodegenerative disease research. By developing R packages, my aim is to create innovative tools and publish research that offer fresh perspectives on data, enabling new discoveries and making a meaningful impact on the medical and scientific community.

## Who is my audience?

Based on my experience, my primary audience consists of fellow researchers working in similar fields. I develop open-source R packages that extract new features from spatial genomics data, aiming to provide unique insights for this type of data. As open-source software, my work is accessible for others to use, improve, or benchmark against, fostering collaboration and progress within the field.

## What is my goal?

My motivation stems from my family, who have been affected by cancer and neurodegenerative diseases, inspiring me to contribute to advancements in disease research. My SpatialFeatures package has been submitted to Bioconductor and received a high distinction grade as my honors project. I can spend countless hours on data analysis projects that intrigue me, thoroughly enjoying the process of discovering new insights step by step. In the next five to ten years, I hope to pursue a PhD with meaningful contributions, graduate successfully, and secure a position in biomedical data science that allows me to continue working on impactful projects.
